"""DEPRECATED: Import from r2inspect.domain.formats.bindiff instead."""

from ..domain.formats.bindiff import (
    calculate_cyclomatic_complexity,
    calculate_rolling_hash,
    categorize_similarity,
    compare_behavioral_features,
    compare_byte_features,
    compare_function_features,
    compare_rolling_hashes,
    compare_string_features,
    compare_structural_features,
    has_crypto_indicators,
    has_network_indicators,
    has_persistence_indicators,
    is_crypto_api,
    is_network_api,
    is_suspicious_api,
    build_struct_signature,
    build_function_signature,
    build_string_signature,
    build_behavioral_signature,
    calculate_overall_similarity,
)

__all__ = [
    "calculate_cyclomatic_complexity",
    "calculate_rolling_hash",
    "categorize_similarity",
    "compare_behavioral_features",
    "compare_byte_features",
    "compare_function_features",
    "compare_rolling_hashes",
    "compare_string_features",
    "compare_structural_features",
    "has_crypto_indicators",
    "has_network_indicators",
    "has_persistence_indicators",
    "is_crypto_api",
    "is_network_api",
    "is_suspicious_api",
    "build_struct_signature",
    "build_function_signature",
    "build_string_signature",
    "build_behavioral_signature",
    "calculate_overall_similarity",
]
