#!/usr/bin/env python3
"""Secondary compiler signatures."""

EXTENDED_COMPILER_SIGNATURES = {
    "VB.NET": {"strings": [r"VB\.NET"], "imports": [], "sections": [], "symbols": []},
    "Managed C++": {
        "strings": [r"Managed C\+\+"],
        "imports": [],
        "sections": [],
        "symbols": [],
    },
    "LLVM": {"strings": [r"LLVM"], "imports": [], "sections": [], "symbols": []},
    "Go Compiler": {"strings": [r"Go Compiler"], "imports": [], "sections": [], "symbols": []},
    "Zig": {"strings": [r"Zig"], "imports": [], "sections": [], "symbols": []},
    "Crystal": {"strings": [r"Crystal"], "imports": [], "sections": [], "symbols": []},
    "D": {"strings": [r"D language"], "imports": [], "sections": [], "symbols": []},
    "Nim": {"strings": [r"Nim"], "imports": [], "sections": [], "symbols": []},
    "Pascal": {"strings": [r"Pascal"], "imports": [], "sections": [], "symbols": []},
    "Fortran": {"strings": [r"Fortran"], "imports": [], "sections": [], "symbols": []},
    "Ada": {"strings": [r"Ada"], "imports": [], "sections": [], "symbols": []},
    "Swift": {"strings": [r"Swift"], "imports": [], "sections": [], "symbols": []},
    "OCaml": {"strings": [r"OCaml"], "imports": [], "sections": [], "symbols": []},
    "Haskell": {"strings": [r"Haskell"], "imports": [], "sections": [], "symbols": []},
    "Erlang": {"strings": [r"Erlang"], "imports": [], "sections": [], "symbols": []},
    "LuaJIT": {"strings": [r"LuaJIT"], "imports": [], "sections": [], "symbols": []},
    "VBA": {"strings": [r"VBA"], "imports": [], "sections": [], "symbols": []},
    "Mono": {"strings": [r"Mono"], "imports": [], "sections": [], "symbols": []},
    "ASM": {"strings": [r"ASM"], "imports": [], "sections": [], "symbols": []},
    "Borland Delphi": {
        "strings": [r"Borland Delphi"],
        "imports": [],
        "sections": [],
        "symbols": [],
    },
    "FPC": {"strings": [r"Free Pascal"], "imports": [], "sections": [], "symbols": []},
    "Racket": {"strings": [r"Racket"], "imports": [], "sections": [], "symbols": []},
    "Vala": {"strings": [r"Vala"], "imports": [], "sections": [], "symbols": []},
    "Cython": {"strings": [r"Cython"], "imports": [], "sections": [], "symbols": []},
    "Microchip": {"strings": [r"Microchip"], "imports": [], "sections": [], "symbols": []},
    "TCC": {"strings": [r"Tiny C Compiler"], "imports": [], "sections": [], "symbols": []},
    "Dev-C++": {"strings": [r"Dev-C\+\+"], "imports": [], "sections": [], "symbols": []},
    "Borland C++ Builder": {
        "strings": [r"C\+\+Builder"],
        "imports": [],
        "sections": [],
        "symbols": [],
    },
    "Microsoft Foundation Classes": {
        "strings": [r"MFC"],
        "imports": [],
        "sections": [],
        "symbols": [],
    },
    "Kylix": {"strings": [r"Kylix"], "imports": [], "sections": [], "symbols": []},
    "Pelles C": {"strings": [r"Pelles"], "imports": [], "sections": [], "symbols": []},
    "OpenWatcom": {"strings": [r"OpenWatcom"], "imports": [], "sections": [], "symbols": []},
    "MetaWare": {"strings": [r"MetaWare"], "imports": [], "sections": [], "symbols": []},
    "IAR": {"strings": [r"IAR"], "imports": [], "sections": [], "symbols": []},
    "SCO": {"strings": [r"SCO"], "imports": [], "sections": [], "symbols": []},
    "IBM XL": {"strings": [r"IBM XL"], "imports": [], "sections": [], "symbols": []},
    "QNX": {"strings": [r"QNX"], "imports": [], "sections": [], "symbols": []},
    "Ti C/C++": {"strings": [r"TI C\+\+"], "imports": [], "sections": [], "symbols": []},
    "Diab": {"strings": [r"Diab"], "imports": [], "sections": [], "symbols": []},
    "Green Hills": {"strings": [r"Green Hills"], "imports": [], "sections": [], "symbols": []},
    "Metrowerks": {"strings": [r"Metrowerks"], "imports": [], "sections": [], "symbols": []},
    "DJGPP": {"strings": [r"DJGPP"], "imports": [], "sections": [], "symbols": []},
    "AIX": {"strings": [r"AIX"], "imports": [], "sections": [], "symbols": []},
    "Sun Studio": {"strings": [r"Sun Studio"], "imports": [], "sections": [], "symbols": []},
    "HP-UX": {"strings": [r"HP-UX"], "imports": [], "sections": [], "symbols": []},
    "NetBSD": {"strings": [r"NetBSD"], "imports": [], "sections": [], "symbols": []},
    "OpenBSD": {"strings": [r"OpenBSD"], "imports": [], "sections": [], "symbols": []},
    "FreeBSD": {"strings": [r"FreeBSD"], "imports": [], "sections": [], "symbols": []},
    "DragonFly": {"strings": [r"DragonFly"], "imports": [], "sections": [], "symbols": []},
    "Haiku": {"strings": [r"Haiku"], "imports": [], "sections": [], "symbols": []},
    "MS-DOS": {"strings": [r"MS-DOS"], "imports": [], "sections": [], "symbols": []},
    "OS/2": {"strings": [r"OS/2"], "imports": [], "sections": [], "symbols": []},
}
