#!/usr/bin/env python3
"""Secondary compiler signatures.

String patterns are matched case-insensitively against the binary's strings.
Bare-word markers are anchored with ``\\b`` word boundaries so a short token
like "Ada" or "SCO" matches the standalone word and not a substring inside an
unrelated string (e.g. the ".NET" marker "metadata" used to score Ada at 1.0).
"""

EXTENDED_COMPILER_SIGNATURES = {
    "VB.NET": {"strings": [r"VB\.NET"], "imports": [], "sections": [], "symbols": []},
    "Managed C++": {
        "strings": [r"Managed C\+\+"],
        "imports": [],
        "sections": [],
        "symbols": [],
    },
    "LLVM": {"strings": [r"\bLLVM\b"], "imports": [], "sections": [], "symbols": []},
    "Go Compiler": {"strings": [r"Go Compiler"], "imports": [], "sections": [], "symbols": []},
    "Zig": {
        "strings": [r"\.zig:", r"/zig/std/", r"zig_probe_stack"],
        "imports": [],
        "sections": [],
        "symbols": [],
    },
    "Crystal": {"strings": [r"\bCrystal\b"], "imports": [], "sections": [], "symbols": []},
    "D": {"strings": [r"D language"], "imports": [], "sections": [], "symbols": []},
    "Nim": {
        "strings": [r"@m[\w./]+\.nim", r"nim_program_result", r"stdlib_\w+\.nim"],
        "imports": [],
        "sections": [],
        "symbols": [],
    },
    "Pascal": {
        "strings": [r"Turbo Pascal", r"Borland Pascal"],
        "imports": [],
        "sections": [],
        "symbols": [],
    },
    "Fortran": {"strings": [r"\bFortran\b"], "imports": [], "sections": [], "symbols": []},
    "Ada": {"strings": [r"\bGNAT\b", r"\badainit\b"], "imports": [], "sections": [], "symbols": []},
    "Swift": {
        "strings": [r"libswiftCore", r"swift_release", r"swift_retain"],
        "imports": [],
        "sections": [],
        "symbols": [],
    },
    "OCaml": {"strings": [r"\bOCaml\b"], "imports": [], "sections": [], "symbols": []},
    "Haskell": {"strings": [r"\bHaskell\b"], "imports": [], "sections": [], "symbols": []},
    "Erlang": {"strings": [r"\bErlang\b"], "imports": [], "sections": [], "symbols": []},
    "LuaJIT": {"strings": [r"\bLuaJIT\b"], "imports": [], "sections": [], "symbols": []},
    "VBA": {"strings": [r"VB[AE][67]\.DLL"], "imports": [], "sections": [], "symbols": []},
    "Mono": {
        "strings": [r"Mono\.Runtime", r"libmono", r"mono-2\.0"],
        "imports": [],
        "sections": [],
        "symbols": [],
    },
    "Borland Delphi": {
        "strings": [r"Borland Delphi"],
        "imports": [],
        "sections": [],
        "symbols": [],
    },
    "FPC": {"strings": [r"Free Pascal"], "imports": [], "sections": [], "symbols": []},
    "Racket": {"strings": [r"\bRacket\b"], "imports": [], "sections": [], "symbols": []},
    "Vala": {"strings": [r"\bVala\b"], "imports": [], "sections": [], "symbols": []},
    "Cython": {"strings": [r"\bCython\b"], "imports": [], "sections": [], "symbols": []},
    "Microchip": {"strings": [r"\bMicrochip\b"], "imports": [], "sections": [], "symbols": []},
    "TCC": {"strings": [r"Tiny C Compiler"], "imports": [], "sections": [], "symbols": []},
    "Dev-C++": {"strings": [r"Dev-C\+\+"], "imports": [], "sections": [], "symbols": []},
    "Borland C++ Builder": {
        "strings": [r"C\+\+Builder"],
        "imports": [],
        "sections": [],
        "symbols": [],
    },
    "Microsoft Foundation Classes": {
        "strings": [r"MFC\d{2,}", r"mfc\d+u?\.dll"],
        "imports": [],
        "sections": [],
        "symbols": [],
    },
    "Kylix": {"strings": [r"\bKylix\b"], "imports": [], "sections": [], "symbols": []},
    "Pelles C": {"strings": [r"\bPelles\b"], "imports": [], "sections": [], "symbols": []},
    "OpenWatcom": {"strings": [r"\bOpenWatcom\b"], "imports": [], "sections": [], "symbols": []},
    "MetaWare": {"strings": [r"\bMetaWare\b"], "imports": [], "sections": [], "symbols": []},
    "IAR": {
        "strings": [r"IAR Systems", r"IAR Embedded Workbench"],
        "imports": [],
        "sections": [],
        "symbols": [],
    },
    "SCO": {
        "strings": [r"SCO OpenServer", r"SCO UNIX"],
        "imports": [],
        "sections": [],
        "symbols": [],
    },
    "IBM XL": {"strings": [r"IBM XL"], "imports": [], "sections": [], "symbols": []},
    "QNX": {
        "strings": [r"QNX Neutrino", r"/usr/qnx"],
        "imports": [],
        "sections": [],
        "symbols": [],
    },
    "Ti C/C++": {"strings": [r"TI C\+\+"], "imports": [], "sections": [], "symbols": []},
    "Diab": {"strings": [r"\bDiab\b"], "imports": [], "sections": [], "symbols": []},
    "Green Hills": {"strings": [r"Green Hills"], "imports": [], "sections": [], "symbols": []},
    "Metrowerks": {"strings": [r"\bMetrowerks\b"], "imports": [], "sections": [], "symbols": []},
    "DJGPP": {"strings": [r"\bDJGPP\b"], "imports": [], "sections": [], "symbols": []},
    "AIX": {
        "strings": [r"IBM XL .*AIX", r"/usr/vac/"],
        "imports": [],
        "sections": [],
        "symbols": [],
    },
    "Sun Studio": {"strings": [r"Sun Studio"], "imports": [], "sections": [], "symbols": []},
    "HP-UX": {"strings": [r"HP-UX"], "imports": [], "sections": [], "symbols": []},
    "NetBSD": {"strings": [r"\bNetBSD\b"], "imports": [], "sections": [], "symbols": []},
    "OpenBSD": {"strings": [r"\bOpenBSD\b"], "imports": [], "sections": [], "symbols": []},
    "FreeBSD": {"strings": [r"\bFreeBSD\b"], "imports": [], "sections": [], "symbols": []},
    "DragonFly": {"strings": [r"\bDragonFly\b"], "imports": [], "sections": [], "symbols": []},
    "Haiku": {"strings": [r"\bHaiku\b"], "imports": [], "sections": [], "symbols": []},
    "MS-DOS": {"strings": [r"MS-DOS"], "imports": [], "sections": [], "symbols": []},
    "OS/2": {
        "strings": [r"OS/2 (Warp|[0-9])"],
        "imports": [],
        "sections": [],
        "symbols": [],
    },
}
