"""DEPRECATED: Import from r2inspect.domain.formats.import_analysis instead."""

from ..domain.formats.import_analysis import (
    NETWORK_CATEGORY,
    INJECTION_APIS,
    ANTI_ANALYSIS_APIS,
    CRYPTO_APIS,
    PERSISTENCE_APIS,
    NETWORK_APIS,
    PROCESS_APIS,
    MEMORY_APIS,
    LOADING_APIS,
    ALL_RISK_API_CATEGORIES,
    build_api_categories,
    categorize_apis,
    assess_api_risk,
    find_suspicious_patterns,
    count_import_categories,
    find_max_risk_score,
    risk_level_from_score,
)

__all__ = [
    "NETWORK_CATEGORY",
    "INJECTION_APIS",
    "ANTI_ANALYSIS_APIS",
    "CRYPTO_APIS",
    "PERSISTENCE_APIS",
    "NETWORK_APIS",
    "PROCESS_APIS",
    "MEMORY_APIS",
    "LOADING_APIS",
    "ALL_RISK_API_CATEGORIES",
    "build_api_categories",
    "categorize_apis",
    "assess_api_risk",
    "find_suspicious_patterns",
    "count_import_categories",
    "find_max_risk_score",
    "risk_level_from_score",
]
