#!/usr/bin/env python3
"""Facade for CLI display section renderers."""

from __future__ import annotations

from .display_sections_common import Results, _get_console
from .display_sections_file import _display_file_info, _display_pe_info, _display_security
from .display_sections_hashing import (
    _add_ccbhash_entries,
    _add_impfuzzy_entries,
    _add_telfhash_entries,
    _add_tlsh_entries,
    _display_ccbhash,
    _display_impfuzzy,
    _display_ssdeep,
    _display_telfhash,
    _display_tlsh,
)
from .display_sections_helpers import (  # noqa: F401
    _add_bindiff_entries,
    _add_bindiff_functions,
    _add_bindiff_signatures,
    _add_bindiff_strings,
    _add_bindiff_structural,
    _add_simhash_feature_stats,
    _add_simhash_function_analysis,
    _add_simhash_hashes,
    _add_simhash_similarity_group,
    _add_simhash_similarity_groups,
    _add_simhash_top_features,
    _format_simhash_hex,
)
from .display_sections_indicators import _display_indicators
from .display_sections_metadata import _add_rich_header_entries, _display_rich_header
from .display_sections_similarity import (
    _add_binbloom_binary_signature,
    _add_binbloom_bloom_stats,
    _add_binbloom_group,
    _add_binbloom_similar_groups,
    _add_binbloom_stats,
    _add_binlex_basic_stats,
    _add_binlex_binary_signatures,
    _add_binlex_entries,
    _add_binlex_similarity_groups,
    _add_binlex_top_ngrams,
    _add_binlex_unique_signatures,
    _display_binbloom,
    _display_binbloom_signature_details,
    _display_bindiff,
    _display_binlex,
    _display_machoc_functions,
    _display_simhash,
)
from .display_statistics import (
    _display_circuit_breaker_statistics,
    _display_most_retried_commands,
    _display_retry_statistics,
)

__all__ = [
    "Results",
    "_get_console",
    "_display_file_info",
    "_display_pe_info",
    "_display_security",
    "_display_ssdeep",
    "_display_tlsh",
    "_display_telfhash",
    "_display_impfuzzy",
    "_display_ccbhash",
    "_display_binlex",
    "_display_binbloom",
    "_display_binbloom_signature_details",
    "_display_simhash",
    "_display_bindiff",
    "_display_machoc_functions",
    "_display_indicators",
    "_display_circuit_breaker_statistics",
    "_display_retry_statistics",
    "_display_most_retried_commands",
    "_display_rich_header",
    "_add_tlsh_entries",
    "_add_telfhash_entries",
    "_add_impfuzzy_entries",
    "_add_ccbhash_entries",
    "_add_binlex_entries",
    "_add_binlex_basic_stats",
    "_add_binlex_unique_signatures",
    "_add_binlex_similarity_groups",
    "_add_binlex_binary_signatures",
    "_add_binlex_top_ngrams",
    "_add_binbloom_stats",
    "_add_binbloom_similar_groups",
    "_add_binbloom_group",
    "_add_binbloom_binary_signature",
    "_add_binbloom_bloom_stats",
    "_add_rich_header_entries",
    "_add_simhash_feature_stats",
    "_add_simhash_hashes",
    "_add_simhash_function_analysis",
    "_add_simhash_top_features",
    "_add_bindiff_entries",
    "_add_bindiff_structural",
    "_add_bindiff_signatures",
    "_add_bindiff_strings",
    "_add_bindiff_functions",
    "_add_simhash_similarity_group",
    "_add_simhash_similarity_groups",
    "_format_simhash_hex",
]
